#!/usr/bin/env python3
import re
import operator
import csv
with open("syslog.log") as file:
  error = {}
  per_user = {}
  for line in file:
    alarm = re.search(r"(INFO|ERROR) ([\w ']*) .*\(([\w\.]*)\)",line)
    if alarm is None:
      continue
    if alarm[1]=="ERROR":
      error[alarm[2]] = error.get(alarm[2],0) +1
    if alarm[3] not in per_user:
      per_user[alarm[3]] = {"INFO":0, "ERROR":0}
      per_user[alarm[3]][alarm[1]] = per_user[alarm[3]].get(alarm[1],0) +1
    else:
      per_user[alarm[3]][alarm[1]] = per_user[alarm[3]].get(alarm[1],0) +1

# check error, per_user
print("{}\n".format(error))
print("{}\n".format(per_user))

# error_message.csv
error2 = sorted(error.items(),key=operator.itemgetter(1), reverse=True)

# check error2 sorted
print("{}\n".format(error2))

error2.insert(0,["Error", "Count"])
with open("error_message.csv", "w") as sw_csv:
  writer = csv.writer(sw_csv)
  writer.writerows(error2)

# user_statistics.csv
user2 = sorted(per_user.items())
user4 = []

# check user2 sorted
print("{}\n".format(user2))

keys = ["Username","INFO","ERROR"]
for user in user2[0:]:
  user3 = []
  user3.append(user[0])
  user3.append(user[1]["INFO"])
  user3.append(user[1]["ERROR"])
  user4.append(list(user3))

# check user4
print("{}\n".format(user4))

user4.insert(0,["Username","INFO","ERROR"])
with open("user_statistics.csv", "w") as usercsv:
  writer = csv.writer(usercsv)
  writer.writerows(user4)