# gen user_emails.csv
with open('user_emails.csv',"w") as file:
  file.write('Full Name, Email Address\n')
  file.write('Blossom Gill, blossom@abc.edu\n')
  file.write('Hayes Delgado, nonummy@utnisia.com\n')
  file.write('Petra Jones, ac@abc.edu\n')
  file.write('Oleg Noel, noel@liberomauris.ca\n')
  file.write('Ahmed Miller, ahmed.miller@nequenonquam.co.uk\n')
  file.write('Macaulay Douglas, mdouglas@abc.edu\n')
  file.write('Aurora Grant, enim.non@abc.edu\n')
  file.write('Madison Mcintosh, mcintosh@nisiaenean.net\n')
  file.write('Montana Powel, montanap@semmagna.org\n')
  file.write('Rogan Robinson, rr.robinson@abc.edu\n')
  file.write('Simon Rivera, sri@abc.edu\n')
  file.write('Benedict Pacheco, bpacheco@abc.edu\n')
  file.write('Maisie Hendrix, mai.hendrix@abc.edu\n')
  file.write('Xaviera Gould, xlg@utnisia.net\n')
  file.write('Oren Rollins, oren@semmagna.com\n')
  file.write('Flavia Santiago, flavia@utnisia.net\n')
  file.write('Jackson Owens, jackowens@abc.edu\n')
  file.write('Britanni Humphrey, britanni@ut.net\n')
  file.write('Kirk Nixon, kirknixon@abc.edu\n')
  file.write('Bree Campbell, breee@utnisia.net\n')
